export { default as project_2_1 } from "./1.webp";
export { default as project_2_2 } from "./2.webp";
export { default as project_2_3 } from "./3.webp";
export { default as project_2_4 } from "./4.webp";
export { default as project_2_5 } from "./5.webp";
export { default as project_2_6 } from "./6.webp";
export { default as project_2_2_1 } from "./2_1.webp";
export { default as project_2_2_2 } from "./2_2.webp";
export { default as project_2_2_3 } from "./2_3.webp";
